function(dy_setup_example target)
    target_link_libraries(${target} PRIVATE ${PROJECT_NAME})
    target_include_directories(${target} PRIVATE ${CMAKE_SOURCE_DIR}/src)
    set_property(TARGET ${target} PROPERTY FOLDER ${target})
    set_property(TARGET ${target} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${target}>")
endfunction()

add_subdirectory(01_HelloWindow)
add_subdirectory(02_HelloRenderer)
add_subdirectory(03_Cube)
add_subdirectory(04_TexturedCube)
add_subdirectory(05_LoadModel)
add_subdirectory(06_ShadowCube)
add_subdirectory(07_RendererStress)
