if(DY_BACKEND_NORMALIZED STREQUAL "D3D12")
	if(NOT WIN32)
		message(FATAL_ERROR "[${PROJECT_NAME}] D3D12 is only supported with Windows OS")
	endif()

	target_compile_definitions(${PROJECT_NAME} PRIVATE ENABLE_D3D12)
	add_subdirectory(src/Backends/D3D12)
elseif(DY_BACKEND_NORMALIZED STREQUAL "METAL")
	if(NOT APPLE)
		message(FATAL_ERROR "[${PROJECT_NAME}] Metal is only supported with Mac OS")
	endif()

	target_compile_definitions(${PROJECT_NAME} PRIVATE ENABLE_METAL)
	add_subdirectory(src/Backends/Metal)
elseif(DY_BACKEND_NORMALIZED STREQUAL "VULKAN")
	target_compile_definitions(${PROJECT_NAME} PRIVATE ENABLE_VULKAN)
	add_subdirectory(src/Backends/Vulkan)
else()
	add_subdirectory(src/Backends/Null)
endif()
