# One support contract selects examples locally and in CI. It is not a GPU capability query.
option(DY_CI "Build offline shader checks and export CI target paths" OFF)
file(READ "${CMAKE_SOURCE_DIR}/.github/ci-support.json" DY_SUPPORT_JSON)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/.github/ci-support.json")

if(USE_D3D12)
    set(DY_SUPPORT_API d3d12)
elseif(USE_METAL)
    set(DY_SUPPORT_API metal)
elseif(USE_VULKAN)
    set(DY_SUPPORT_API vulkan)
else()
    set(DY_SUPPORT_API null)
endif()

function(dy_support_has_check output item api check)
    set(apis "${api}")
    if(api STREQUAL "null")
        # Only common CPU checks belong to the auxiliary job; API-specific checks stay
        # in their own backend jobs. Ordinary local Null builds keep common examples.
        set(apis vulkan d3d12 metal)
        if(DY_CI)
            set(check cpu)
        else()
            set(check build)
        endif()
    endif()
    foreach(graphics_api IN LISTS apis)
        string(JSON checks GET "${DY_SUPPORT_JSON}" items "${item}" apis "${graphics_api}" checks)
        string(FIND "${checks}" "\"${check}\"" position)
        if(position EQUAL -1)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${output} TRUE PARENT_SCOPE)
endfunction()

function(dy_ci_shader_checks item target directory)
    dy_support_has_check(check_shaders "${item}" "${DY_SUPPORT_API}" shader)
    if(NOT DY_CI OR NOT check_shaders OR DY_SUPPORT_API STREQUAL "null")
        return()
    endif()
    set(glsl_vertex vert)
    set(glsl_fragment frag)
    set(glsl_compute comp)
    set(hlsl_vertex vs_5_1)
    set(hlsl_fragment ps_5_1)
    set(hlsl_compute cs_5_1)
    string(JSON count LENGTH "${DY_SUPPORT_JSON}" items "${item}" apis "${DY_SUPPORT_API}" shaders)
    math(EXPR last "${count} - 1")
    set(outputs)
    # Common includes also invalidate offline shader outputs on incremental builds.
    file(GLOB_RECURSE includes CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/src/*.inc"
        "${CMAKE_SOURCE_DIR}/src/*.h" "${directory}/Shaders/*.inc")
    foreach(index RANGE ${last})
        string(JSON source GET "${DY_SUPPORT_JSON}" items "${item}" apis "${DY_SUPPORT_API}" shaders ${index} source)
        string(JSON stage GET "${DY_SUPPORT_JSON}" items "${item}" apis "${DY_SUPPORT_API}" shaders ${index} stage)
        set(input "${directory}/${source}")
        if(NOT EXISTS "${input}")
            message(FATAL_ERROR "${item}/${DY_SUPPORT_API}: missing shader ${input}")
        endif()
        if(DY_SUPPORT_API STREQUAL "vulkan")
            set(compiler glslc)
            set(extension spv)
            set(options "-fshader-stage=${glsl_${stage}}" -I "${CMAKE_SOURCE_DIR}/src" "${input}" -o)
        elseif(DY_SUPPORT_API STREQUAL "d3d12")
            set(compiler fxc)
            set(extension dxbc)
            set(options /nologo /enable_unbounded_descriptor_tables
                /E main /T "${hlsl_${stage}}" /I "${CMAKE_SOURCE_DIR}/src"
                "$<$<CONFIG:Debug>:/Zi>" "$<$<CONFIG:Debug>:/Od>" "${input}" /Fo)
        else()
            set(compiler xcrun)
            set(extension air)
            set(options -sdk macosx metal -c "${input}" -I "${CMAKE_SOURCE_DIR}/src" -o)
        endif()
        find_program(DY_CI_SHADER_COMPILER NAMES "${compiler}" REQUIRED
            HINTS "$ENV{VULKAN_SDK}/Bin" "$ENV{VULKAN_SDK}/bin" "$ENV{WindowsSdkVerBinPath}/x64")
        set(output "${CMAKE_BINARY_DIR}/ci-shaders/$<CONFIG>/${item}/${source}.${extension}")
        get_filename_component(output_dir "${output}" DIRECTORY)
        add_custom_command(OUTPUT "${output}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${output_dir}"
            COMMAND "${DY_CI_SHADER_COMPILER}" ${options} "${output}"
            DEPENDS "${input}" ${includes}
            COMMAND_EXPAND_LISTS VERBATIM)
        list(APPEND outputs "${output}")
    endforeach()
    add_custom_target("ci_shaders_${item}" ALL DEPENDS ${outputs})
    add_dependencies("ci_shaders_${item}" "${target}")
endfunction()

string(JSON item_count LENGTH "${DY_SUPPORT_JSON}" items)
if(item_count LESS 1)
    message(STATUS "No examples or feature checks registered")
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/ci-targets-$<CONFIG>.json" CONTENT "{}\n")
    return()
endif()
math(EXPR item_last "${item_count} - 1")
set(target_entries)
foreach(index RANGE ${item_last})
    string(JSON item MEMBER "${DY_SUPPORT_JSON}" items ${index})
    string(JSON target GET "${DY_SUPPORT_JSON}" items "${item}" target)
    string(JSON directory GET "${DY_SUPPORT_JSON}" items "${item}" directory)
    if(NOT directory MATCHES "^examples/[A-Za-z0-9_/-]+$" OR directory MATCHES "\\.\\."
        OR NOT target MATCHES "^[A-Za-z0-9_]+$")
        message(FATAL_ERROR "Invalid example path or target in support contract: ${item}")
    endif()
    if(NOT EXISTS "${CMAKE_SOURCE_DIR}/${directory}/CMakeLists.txt")
        message(FATAL_ERROR "Declared example directory is missing: ${directory}")
    endif()
    dy_support_has_check(selected "${item}" "${DY_SUPPORT_API}" build)
    if(NOT selected)
        message(STATUS "${item}/${DY_SUPPORT_API}: no example build registered")
        continue()
    endif()
    # A feature can select its example before the example's own entry is visited.
    if(NOT TARGET "${target}")
        add_subdirectory("${CMAKE_SOURCE_DIR}/${directory}" "${CMAKE_BINARY_DIR}/${directory}")
    endif()
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "${item}/${DY_SUPPORT_API}: missing declared target ${target}")
    endif()
    list(APPEND target_entries "\"${target}\":\"$<TARGET_FILE:${target}>\"")
    dy_ci_shader_checks("${item}" "${target}" "${CMAKE_SOURCE_DIR}/${directory}")
endforeach()

list(REMOVE_DUPLICATES target_entries)
list(JOIN target_entries ",\n" target_json)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/ci-targets-$<CONFIG>.json"
    CONTENT "{\n${target_json}\n}\n")
